export { areEqualValues } from "./areEqualValues";
export { clamp } from "./clamp";
export { extractThumbCoordsFromMouseEvent, extractThumbCoordsFromTouchEvent } from "./extractThumbCoords";
export { getOffsetStyle, getLeapStyle } from "./getAxisParams";
export { getNearestValueFromArray, getNearestValueFromStep, getNearestValueIndex } from "./getNearestValue";
export { getOwnerDocument } from "./getOwnerDocument";
export { getIsDraggingStyle, getInputStyle } from "./getStyles";
export { getTargetIndex } from "./getTargetIndex";
export { getThumbMoveType } from "./getThumbMoveType";
export { getThumbNewValue } from "./getThumbNewValue";
export { getTrack, type Track } from "./getTrackData";
export { getValuesArr } from "./getValuesArr";
export { getMarksFromParams, getMarksValues } from "./marks";
export { setNewValue } from "./setNewValue";
export { valueConverter } from "./valueConverter";