export { areEqualValues } from "./areEqualValues";
export { clamp } from "./clamp";
export { extractThumbCoordsFromMouseEvent, extractThumbCoordsFromTouchEvent } from "./extractThumbCoords";
export { getOffsetStyle, getLeapStyle } from "./getAxisParams";
export { getNearestValueFromArray, getNearestValueFromStep } from "./getNearestValue";
export { getOwnerDocument } from "./getOwnerDocument";
export { getThumbMoveType } from "./getThumbMoveType";
export { getThumbNewValue } from "./getThumbNewValue";
export { getTrack, type Track } from "./getTrackData";
export { getValuesArr } from "./getValues";
export { getMarksFromParams, getMarksValues } from "./marks";
export { valueConverter } from "./valueConverter";